name: Generate 2-Month Spread Charts

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: true  # Needed to push

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pandas matplotlib

    - name: Run spread generator
      run: |
        python generate_spread_charts_html.py --dir coffee_data --out spreads.html

    - name: Commit and push generated charts & HTML
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add coffee_data/charts/* coffee_data/spreads.html
        git diff --cached --quiet || git commit -m "Update 2-month spreads [skip ci]"
        git push
