name: Monthly Coffee Futures Update

on:
  workflow_dispatch:     # allow manual trigger
  schedule:
    - cron: "0 6 1 * *"  # run at 06:00 UTC on the 1st of each month

permissions:
  contents: write        # allow pushing back to the repo

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run download script
        run: |
          rm -rf coffee_data index.html || true
          python download_coffee.py

      - name: Commit and push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add coffee_data/*.csv index.html || true
          git commit -m "Monthly update of coffee futures data" || echo "No changes to commit"
          git push
